### ISSUE TITLE
Saving API Key and Secret Key in .env file fails

### ISSUE THREAD

**Issue by amorebise** [Hng-X/moneywave-php#4]
Saving the API key and Secret key inside the .env file fails. I still had to manually call the class as shown: 

`$mw = new \HngX\Moneywave\Moneywave($youApiKey, $yourSecretKey);` 

A bug?

**Comment by shalvah** [comment]
What did you save them as?

**Comment by amorebise** [comment]
MONEYWAVE_API_KEY
MONEYWAVE_SECRET_KEY

**Comment by shalvah** [comment]
I just taged a new release which should fix this. Do try it out and let me know the outcome

**Comment by amorebise** [comment]
OK, I will check it out.
