### ISSUE TITLE
Class 'HngX\Moneywave\Transaction\CardToAccountTransaction' not found

### ISSUE THREAD

**Issue by amorebise** [Hng-X/moneywave-php#5]
I have no clue as to why I get an error message that this class is not found when I know it is in the package directory. The _HngX\Moneywave\Transaction\WalletToAccountTransaction;_ seems to be working. 

What could be going on?

**Comment by shalvah** [comment]
Do all other classes work well?

**Comment by shalvah** [comment]
The class name is `HngX\Moneywave\Transactions\WalletToAccountTransaction` though. Please check that you added the _s_ in `\Transactions\`

**Comment by amorebise** [comment]
It was a typo. I missed out the `s`. Yikes!

**Comment by shalvah** [comment]
Lol... Why not use an IDE like PHPStorm, soyour classes can be imported automatically?

**Comment by amorebise** [comment]
I am having to code online... **C9 IDE**. I do not think it is able to do that for me.

**Comment by shalvah** [comment]
Oh, okay.
